const fs = require('fs')
const path = require('path')
const assert = require('assert')

const root = path.resolve(__dirname, '..')
const reader = fs.readFileSync(path.join(root, 'static/reader.js'), 'utf8')
const css = fs.readFileSync(path.join(root, 'static/reader.css'), 'utf8')
const view = fs.readFileSync(path.join(root, 'static/foliate-reader/view.js'), 'utf8')
for (const marker of ["import('./epub.js')", "import('./mobi.js')", "import('./fb2.js')", "import('./pdf.js')", "isFBZ(file)", "isFB2(file)"]) assert.ok(view.includes(marker), marker)
for (const file of ['epub.js', 'mobi.js', 'fb2.js', 'pdf.js', 'view.js', 'progress.js', 'ui/tree.js']) assert.ok(fs.existsSync(path.join(root, 'static/foliate-reader', file)), file)
assert.match(fs.readFileSync(path.join(root, 'static/foliate-reader/mobi.js'), 'utf8'), /createDocument/)
assert.match(fs.readFileSync(path.join(root, 'static/foliate-reader/fb2.js'), 'utf8'), /resolveHref/)
assert.match(fs.readFileSync(path.join(root, 'static/foliate-reader/epub.js'), 'utf8'), /String\(href \?\? ''\)/)
const foliateReader = fs.readFileSync(path.join(root, 'static/foliate-reader/reader.js'), 'utf8')
for (const message of ['voice-foliate-goto-cfi', 'voice-foliate-search', 'voice-foliate-seek', 'voice-foliate-prev', 'voice-foliate-next']) assert.ok(foliateReader.includes(message), message)

assert.strictEqual((reader.match(/async function renderFoliate\(/g) || []).length, 1)
assert.strictEqual(reader.includes('renderFoliateClean'), false)
assert.strictEqual(reader.includes('EventTarget.prototype.addEventListener'), false)
assert.strictEqual(reader.includes('foliate-continuous-section'), true)
assert.strictEqual(reader.includes('document.querySelector("#toc-list").addEventListener'), false)
assert.strictEqual(reader.includes('activateFoliateTocEntryLatest'), false)
assert.strictEqual(reader.includes('setupFoliateToc'), false)
assert.strictEqual(reader.includes('foliateVisibleSections'), false)
assert.strictEqual(reader.includes('foliateVisibleNodes'), false)
assert.strictEqual(reader.includes('directFoliateMoving'), false)
assert.strictEqual(reader.includes('directFoliateContainer'), false)
assert.strictEqual(reader.includes('setInterval(() => { loadNextFoliateSection(); }, 100)'), false)
assert.strictEqual(reader.includes('setInterval(() => { const tab = document.querySelector("#toc-tab")'), false)
assert.strictEqual(reader.includes('setInterval('), false)
assert.match(reader, /function scheduleFoliateScrollSync\(\)/)
assert.match(reader, /foliateSectionObserver\?\.disconnect\(\)/)
assert.strictEqual((reader.match(/function disposeReader\(\)/g) || []).length, 1)
assert.strictEqual((reader.match(/function setReaderPhase\(/g) || []).length, 1)
assert.strictEqual((reader.match(/function classifyReaderError\(/g) || []).length, 1)
assert.match(reader, /const readerLifecycle = readerRuntime\.state\.lifecycle/)
assert.doesNotMatch(reader, /(?:^|\n)\s*let readerStage\b/)
assert.match(reader, /readerRuntime\.setStage\(stage\)/)
assert.match(reader, /\$\{readerLifecycle\.stage\}/)
assert.match(reader, /function scheduleSave\(\) \{ if \(readerLifecycle\.disposed\) return;/)
assert.match(reader, /if \(readerLifecycle\.disposed \|\| !documentState\.restorationReady/)
assert.strictEqual((reader.match(/if \(!setReaderPhase\("ready"\)\) return/g) || []).length, 2)
assert.match(reader, /addEventListener\("pagehide"/)
assert.match(reader, /event\.persisted/)
assert.match(reader, /!event\.persisted/)
assert.doesNotMatch(reader, /id=["']ocr["']/i)
assert.match(reader, /validatePdfPageManifest/)
assert.match(reader, /chapterManifestObserver\?\.disconnect\(\)/)
assert.match(reader, /content\.dataset\.errorCode = code/)
assert.match(reader, /reader-request-manager\.js/)
assert.match(reader, /VoiceOfMLReaderRequests\.createReaderRequestManager\(\)/)
assert.match(reader, /readerRuntime\.track\(readerRequestManager\)/)
for (const generation of ['navigation', 'search', 'bookmarks', 'pdf']) assert.match(reader, new RegExp(`nextReaderGeneration\\("${generation}"\\)`))
for (const timer of ['saveTimer', 'themeAnimationTimer', 'panelAnimationTimer']) assert.match(reader, new RegExp(`clearTimeout\\(${timer}\\)`))
for (const frame of ['markerFrame', 'foliateScrollFrame', 'epubSeekFrame']) assert.match(reader, new RegExp(`cancelAnimationFrame\\(${frame}\\)`))
assert.match(reader, /pdfDocument\?\.destroy\?\.\(\)/)
assert.match(reader, /mediaElement\.pause\(\)/)
assert.match(reader, /mediaElement\.removeAttribute\("src"\)/)
assert.strictEqual(reader.includes('activeReaderControllers'), false)
assert.strictEqual(reader.includes('readerRequests'), false)
assert.match(reader, /function syncTocTab\(\)/)
assert.match(reader, /function applyReaderMetadata\(data\)/)
assert.strictEqual((reader.match(/function applyReaderMetadata\(data\)/g) || []).length, 1)
assert.ok(reader.indexOf('const viewport = document.querySelector("#viewport")') < reader.indexOf('applyReaderMetadata(resolvedReaderData);'))
assert.match(reader, /article\.querySelectorAll\("style,link\[rel=stylesheet\]"\)/)
assert.strictEqual((reader.match(/async function renderByMode\(prepared\)/g) || []).length, 1)
assert.match(reader, /await formatAdapters\.active\.render\(prepared\)/)
assert.strictEqual((reader.match(/function loadPdfDocument\(\)/g) || []).length, 1)
for (const renderer of ['renderImageDocument', 'renderMediaDocument']) assert.strictEqual((reader.match(new RegExp(`function ${renderer}\\(`,'g')) || []).length, 1)
for (const renderer of ['renderTextDocument', 'renderMarkdownDocument']) assert.strictEqual((reader.match(new RegExp(`function ${renderer}\\(`,'g')) || []).length, 1)
for (const loader of ['loadTextDocument', 'loadMarkdownDocument', 'loadHtmlDocument', 'loadDocxDocument']) assert.strictEqual((reader.match(new RegExp(`function ${loader}\\(`,'g')) || []).length, 1)
for (const loader of ['loadMediaDocument', 'loadImageDocument', 'loadChapterManifestDocument', 'loadFoliateDocument']) assert.strictEqual((reader.match(new RegExp(`function ${loader}\\(`,'g')) || []).length, 1)
assert.match(reader, /reader-chapter-repository\.js/)
assert.match(reader, /reader-scroll-anchor\.js/)
assert.match(reader, /reader-section-virtualizer\.js/)
assert.match(reader, /VoiceOfMLReaderChapters\.createChapterRepository\(/)
assert.match(reader, /VoiceOfMLReaderScroll\.createScrollAnchorManager\(/)
assert.match(reader, /VoiceOfMLReaderVirtual\.createSectionVirtualizer\(/)
assert.match(reader, /foliateChapterRepository\?\.dispose\(\)/)
assert.match(reader, /readerRuntime\.track\(VoiceOfMLReaderScroll/)
assert.match(reader, /foliateSectionVirtualizer\?\.dispose\(\)/)
assert.match(reader, /function foliateSectionRoot\(article\)/)
assert.match(reader, /article\.attachShadow\(\{ mode: "open" \}\)/)
assert.match(reader, /event\.composedPath\(\)/)
assert.match(reader, /foliateSectionRoot\(node\)/)
assert.match(reader, /foliateScrollAnchors\.observe\(article\)/)
assert.ok((reader.match(/foliateScrollAnchors\.invalidate\(\)/g) || []).length >= 3)
const renderFoliateSource = reader.match(/async function renderFoliate\([\s\S]*?status\.textContent = "EPUB";\n}/)[0]
assert.strictEqual(renderFoliateSource.includes('loaded = new Set'), false)
assert.strictEqual(renderFoliateSource.includes('pending = new Map'), false)
assert.match(reader, /stream\.insertBefore\(article, next \|\| null\)/)
assert.match(reader, /foliateSectionLoader = \(index\)/)
assert.doesNotMatch(reader, /navigationGeneration/)
assert.doesNotMatch(reader, /syncReaderState/)
for (const mirror of ['title', 'zoom', 'currentPage', 'pageCount', 'restoredEntry', 'restorationReady', 'tocEntries', 'currentChapterIndex', 'fullSearchResults', 'fullSearchIndex', 'fullSearchGeneration', 'showingAllBookmarks', 'editingBookmark', 'pdfRenderGeneration']) assert.doesNotMatch(reader, new RegExp(`(?:let|var|const)\\s+${mirror}\\b`), mirror)
assert.doesNotMatch(reader, /readerRuntime\.updateFormat\(/)
for (const domain of ['document', 'navigation', 'search', 'panel']) assert.match(reader, new RegExp(`readerRuntime\\.state\\.${domain}`))
assert.match(reader, /readerRuntime\.currentGeneration\("pdf"\)/)
assert.match(reader, /const generation = nextReaderGeneration\("search"\)/)
assert.match(reader, /isReaderGenerationCurrent\("navigation", generation\)/)
assert.match(reader, /registerReaderFormatAdapters\(\)/)
assert.match(reader, /function disposeFormatResources\(mode\)/)
assert.match(reader, /function navigateFormat\(mode, value\)/)
assert.match(reader, /link\.target = "_blank"; link\.rel = "noopener noreferrer"/)
assert.match(reader, /function searchFormat\(mode, query\)/)
assert.match(reader, /async function restoreFormat\(mode, entry\)/)
assert.match(reader, /formatAdapters\.activate\(capability\.mode\)/)
assert.match(reader, /readerRuntime\.events\.on\("phase"/)
assert.strictEqual((reader.match(/function navigateTocEntry\(/g) || []).length, 1)
assert.match(reader, /await navigateTocEntry\(index\)/)
assert.strictEqual((reader.match(/function navigateFoliateSearchResult\(/g) || []).length, 1)
assert.strictEqual(reader.includes('if (false && capability.mode === "foliate")'), false)
assert.match(reader, /function captureFoliateBookmarkPosition\(\)/)
assert.match(reader, /function restoreFoliateBookmarkPosition\(entry\)/)
assert.match(reader, /foliatePosition = captureFoliateBookmarkPosition\(\)/)
assert.match(reader, /new IntersectionObserver/)
assert.doesNotMatch(reader, /article\.innerHTML = styles \+/)
assert.match(reader, /target = await epubRendition\?\.book\?\.resolveHref/)
assert.match(reader, /applyReaderMetadata\(resolvedReaderData\)/)
assert.match(css, /\.foliate-continuous a \{ color: #8ab4e8 !important; \}/)
assert.match(css, /min-height: 0 !important; height: auto !important;/)
assert.strictEqual(view.includes('.find(x => x.index = resolved.index)'), false)
assert.strictEqual(view.includes('.find(x => x.index === resolved.index)'), true)
console.log('reader architecture contracts passed')
