const fs = require('fs')
const path = require('path')
const assert = require('assert')
const { assertCode, codePattern } = require('./reader_source_contract')

const root = path.resolve(__dirname, '..')
const reader = fs.readFileSync(path.join(root, 'static/reader.js'), 'utf8')
const css = fs.readFileSync(path.join(root, 'static/reader.css'), 'utf8')
const view = fs.readFileSync(path.join(root, 'static/foliate-reader/view.js'), 'utf8')
for (const marker of ["import('./epub.js')", "import('./mobi.js')", "import('./fb2.js')", "import('./pdf.js')", "isFBZ(file)", "isFB2(file)"]) assert.ok(view.includes(marker), marker)
for (const file of ['epub.js', 'mobi.js', 'fb2.js', 'pdf.js', 'view.js', 'progress.js', 'ui/tree.js']) assert.ok(fs.existsSync(path.join(root, 'static/foliate-reader', file)), file)
assert.match(fs.readFileSync(path.join(root, 'static/foliate-reader/mobi.js'), 'utf8'), /createDocument/)
assert.match(fs.readFileSync(path.join(root, 'static/foliate-reader/fb2.js'), 'utf8'), /resolveHref/)
assert.match(fs.readFileSync(path.join(root, 'static/foliate-reader/epub.js'), 'utf8'), /String\(href \?\? ''\)/)
const foliateReader = fs.readFileSync(path.join(root, 'static/foliate-reader/reader.js'), 'utf8')
for (const message of ['voice-foliate-goto-cfi', 'voice-foliate-search', 'voice-foliate-seek', 'voice-foliate-prev', 'voice-foliate-next']) assert.ok(foliateReader.includes(message), message)

assert.strictEqual((reader.match(/async function renderFoliate\(/g) || []).length, 1)
assert.strictEqual(reader.includes('renderFoliateClean'), false)
assert.strictEqual(reader.includes('EventTarget.prototype.addEventListener'), false)
assertCode(reader, 'stream.className = "foliate-continuous"')
assert.strictEqual(reader.includes('document.querySelector("#toc-list").addEventListener'), false)
assert.strictEqual(reader.includes('activateFoliateTocEntryLatest'), false)
assert.strictEqual(reader.includes('setupFoliateToc'), false)
assert.strictEqual(reader.includes('foliateVisibleSections'), false)
assert.strictEqual(reader.includes('foliateVisibleNodes'), false)
assert.strictEqual(reader.includes('directFoliateMoving'), false)
assert.strictEqual(reader.includes('directFoliateContainer'), false)
assert.strictEqual(reader.includes('setInterval(() => { loadNextFoliateSection(); }, 100)'), false)
assert.strictEqual(reader.includes('setInterval(() => { const tab = document.querySelector("#toc-tab")'), false)
assert.strictEqual(reader.includes('setInterval('), false)
assert.match(reader, /function scheduleFoliateScrollSync\(\)/)
assert.match(reader, /foliateSectionObserver\?\.disconnect\(\)/)
assert.strictEqual((reader.match(/function disposeReader\(\)/g) || []).length, 1)
assert.strictEqual((reader.match(/function setReaderPhase\(/g) || []).length, 1)
assert.strictEqual((reader.match(/function classifyReaderError\(/g) || []).length, 1)
assert.match(reader, /const readerLifecycle = readerRuntime\.state\.lifecycle/)
assert.doesNotMatch(reader, /(?:^|\n)\s*let readerStage\b/)
assert.match(reader, /readerRuntime\.setStage\(stage\)/)
assert.match(reader, /\$\{readerLifecycle\.stage\}/)
assertCode(reader, 'function scheduleSave() { if (readerLifecycle.disposed || readerAbortController.signal.aborted) return;')
assertCode(reader, 'readerLifecycle.disposed || !documentState.restorationReady')
assert.strictEqual((reader.match(/if \(!setReaderPhase\("ready"\)\) return/g) || []).length, 2)
assert.match(reader, /addEventListener\("pagehide"/)
assert.match(reader, /event\.persisted/)
assert.match(reader, /!event\.persisted/)
assert.doesNotMatch(reader, /id=["']ocr["']/i)
assert.match(reader, /validatePdfPageManifest/)
assert.match(reader, /chapterManifestObserver\?\.disconnect\(\)/)
assert.match(reader, /content\.dataset\.errorCode = code/)
assert.match(reader, /reader-request-manager\.js/)
assert.match(reader, /VoiceOfMLReaderRequests\.createReaderRequestManager\(\)/)
assert.match(reader, /readerRuntime\.track\(readerRequestManager\)/)
for (const generation of ['navigation', 'search', 'bookmarks', 'pdf']) assert.match(reader, new RegExp(`nextReaderGeneration\\("${generation}"\\)`))
for (const timer of ['saveTimer', 'themeAnimationTimer', 'panelAnimationTimer']) assert.match(reader, new RegExp(`clearTimeout\\(${timer}\\)`))
assertCode(reader, 'for (const frame of [markerFrame, foliateScrollFrame, foliateWindowFrame, epubSeekFrame]) if (frame) cancelAnimationFrame(frame)')
assertCode(reader, 'trackReaderResource(destroy)')
assertCode(reader, 'task.destroy()')
assert.match(reader, /mediaElement\.pause\(\)/)
assert.match(reader, /mediaElement\.removeAttribute\("src"\)/)
assert.strictEqual(reader.includes('activeReaderControllers'), false)
assert.strictEqual(reader.includes('readerRequests'), false)
assert.match(reader, /function syncTocTab\(\)/)
assert.match(reader, /function applyReaderMetadata\(data\)/)
assert.strictEqual((reader.match(/function applyReaderMetadata\(data\)/g) || []).length, 1)
const viewportDeclaration = codePattern('const viewport = document.querySelector("#viewport")').exec(reader)
const metadataApplication = codePattern('applyReaderMetadata(resolvedReaderData)').exec(reader)
assert.ok(viewportDeclaration && metadataApplication && viewportDeclaration.index < metadataApplication.index)
assertCode(reader, 'formatAdapters.active.open()')
assertCode(reader, 'await formatAdapters.active.render(prepared)')
assertCode(reader, 'await restoreInitialPosition(documentState.restoredEntry, generation)')
assertCode(reader, 'await formatAdapters.active.restore(entry, generation)')
assert.strictEqual((reader.match(/function loadPdfDocument\(\)/g) || []).length, 1)
for (const renderer of ['renderImageDocument', 'renderMedia']) assert.strictEqual((reader.match(new RegExp(`function ${renderer}\\s*\\(`,'g')) || []).length, 1)
for (const renderer of ['renderTextDocument', 'renderMarkdownDocument']) assert.strictEqual((reader.match(new RegExp(`function ${renderer}\\(`,'g')) || []).length, 1)
for (const loader of ['loadTextDocument', 'loadMarkdownDocument', 'loadHtmlDocument', 'loadDocxDocument']) assert.strictEqual((reader.match(new RegExp(`function ${loader}\\(`,'g')) || []).length, 1)
for (const loader of ['loadMediaDocument', 'loadImageDocument', 'loadChapterManifestDocument']) assert.strictEqual((reader.match(new RegExp(`function ${loader}\\(`,'g')) || []).length, 1)
assert.doesNotMatch(reader, /loadFoliateDocument/)
assert.match(reader, /reader-chapter-repository\.js/)
assert.match(reader, /reader-scroll-anchor\.js/)
assert.match(reader, /reader-section-virtualizer\.js/)
assert.match(reader, /VoiceOfMLReaderChapters\.createChapterRepository\(/)
assert.match(reader, /VoiceOfMLReaderScroll\.createScrollAnchorManager\(/)
assert.match(reader, /VoiceOfMLReaderVirtual\.createSectionVirtualizer\(/)
assert.match(reader, /foliateChapterRepository\?\.dispose\(\)/)
assertCode(reader, 'readerRuntime.track(VoiceOfMLReaderScroll')
assert.match(reader, /foliateSectionVirtualizer\?\.dispose\(\)/)
assert.match(reader, /function foliateSectionRoot\(article\)/)
assertCode(reader, 'article.attachShadow({ mode: "open" })')
assert.match(reader, /event\.composedPath\(\)/)
assert.match(reader, /foliateSectionRoot\(node\)/)
assert.match(reader, /foliateScrollAnchors\.observe\(article\)/)
assert.ok((reader.match(/foliateScrollAnchors\.invalidate\(\)/g) || []).length >= 3)
const renderFoliateSource = reader.match(/async\s+function\s+renderFoliate\s*\([\s\S]*?status\.textContent\s*=\s*"EPUB";/)[0]
assert.strictEqual(renderFoliateSource.includes('loaded = new Set'), false)
assert.strictEqual(renderFoliateSource.includes('pending = new Map'), false)
assert.match(reader, /stream\.insertBefore\(article, next \|\| null\)/)
assert.match(reader, /foliateSectionLoader = \(index\)/)
assert.doesNotMatch(reader, /^let navigationGeneration\b/m)
assert.doesNotMatch(reader, /syncReaderState/)
assert.doesNotMatch(reader, /^(?:let|var|const)\s+title\b/m)
for (const mirror of ['zoom', 'currentPage', 'pageCount', 'restoredEntry', 'restorationReady', 'tocEntries', 'currentChapterIndex', 'fullSearchResults', 'fullSearchIndex', 'fullSearchGeneration', 'showingAllBookmarks', 'editingBookmark', 'pdfRenderGeneration']) assert.doesNotMatch(reader, new RegExp(`(?:let|var|const)\\s+${mirror}\\b`), mirror)
assert.doesNotMatch(reader, /readerRuntime\.updateFormat\(/)
for (const domain of ['document', 'navigation', 'search', 'panel']) assert.match(reader, new RegExp(`readerRuntime\\.state\\.${domain}`))
assert.match(reader, /readerRuntime\.currentGeneration\("pdf"\)/)
assert.match(reader, /const generation = nextReaderGeneration\("search"\)/)
assert.match(reader, /isReaderGenerationCurrent\("navigation", generation\)/)
assert.match(reader, /registerReaderFormatAdapters\(\)/)
assert.match(reader, /function disposeFormatResources\(mode\)/)
assert.doesNotMatch(reader, /function (?:navigateFormat|searchFormat)\(/)
assertCode(reader, 'link.target = "_blank"; link.rel = "noopener noreferrer"')
assert.match(reader, /async function restoreFormat\(mode, entry, generation/)
assert.match(reader, /formatAdapters\.activate\(capability\.mode\)/)
assert.match(reader, /readerRuntime\.events\.on\("phase"/)
assert.strictEqual((reader.match(/function navigateTocEntry\(/g) || []).length, 1)
assert.match(reader, /await navigateTocEntry\(index\)/)
assert.strictEqual((reader.match(/function navigateFoliateSearchResult\(/g) || []).length, 1)
assert.strictEqual((reader.match(/function\s+fullSearchFoliateMatches\s*\(/g) || []).length, 1)
assertCode(reader, 'publishSearchResults(generation, await fullSearchFoliateMatches(query, generation))')
assert.strictEqual(reader.includes('if (false && capability.mode === "foliate")'), false)
assert.match(reader, /function captureFoliateBookmarkPosition\(\)/)
assert.match(reader, /function restoreFoliateBookmarkPosition\(entry, generation/)
assert.match(reader, /foliatePosition = captureFoliateBookmarkPosition\(\)/)
assert.match(reader, /new IntersectionObserver/)
assert.doesNotMatch(reader, /article\.innerHTML = styles \+/)
assert.match(reader, /target = await epubRendition\?\.book\?\.resolveHref/)
assert.match(reader, /applyReaderMetadata\(resolvedReaderData\)/)
assert.match(css, /\.foliate-continuous\s+a\s*\{\s*color:\s*#8ab4e8\s*!important;\s*\}/)
assert.match(css, /min-height:\s*0\s*!important;\s*height:\s*auto\s*!important;/)
assert.strictEqual(view.includes('.find(x => x.index = resolved.index)'), false)
assert.strictEqual(view.includes('.find(x => x.index === resolved.index)'), true)
const vm = require('vm')
const sandbox = { self: {} }; sandbox.self = sandbox;
function loadExports(file, name) { vm.runInNewContext(fs.readFileSync(path.join(root, 'static', file), 'utf8'), sandbox); return sandbox[name]; }
const contractFeatures = loadExports('reader-contract.js', 'VoiceOfMLReader').features
const runtimeMatrix = loadExports('reader-runtime.js', 'VoiceOfMLReaderRuntime').FEATURE_MATRIX
assert.strictEqual(runtimeMatrix, contractFeatures)
for (const mode of Object.keys(contractFeatures)) assert.strictEqual(JSON.stringify(runtimeMatrix[mode]), JSON.stringify(contractFeatures[mode]), mode)
assert.strictEqual(JSON.stringify(runtimeMatrix.unsupported), JSON.stringify({ toc: false, search: false, zoom: false, bookmarks: false, pagination: false, media: false }))
// Evaluate the owning registry with identifiable loaders/renderers, so comments or
// dead dispatch functions cannot satisfy the format wiring contract.
const registry = reader.match(/function\s+registerReaderFormatAdapters\s*\(\)\s*\{[\s\S]*?\n\}/)
assert.ok(registry, 'format adapter registry')
const expected = {
  pdf: ['loadPdfDocument', 'renderPdf'], image: ['loadImageDocument', 'renderImageDocument'],
  text: ['loadTextDocument', 'renderTextDocument'], markdown: ['loadMarkdownDocument', 'renderMarkdownDocument'],
  html: ['loadHtmlDocument', 'renderHtml'], 'epub-chapters': ['loadChapterManifestDocument', 'renderChapterManifest'],
  docx: ['loadDocxDocument', 'renderDocx'], foliate: ['loadMediaDocument', 'renderFoliate'],
}
const registered = new Map(), calls = []
const registryContext = { formatAdapters: { register: (mode, adapter) => registered.set(mode, adapter) } }
for (const name of [...new Set(Object.values(expected).flat()), 'preloadPdfFirstPage', 'fetchReaderResponse', 'renderPdfPages', 'renderMedia', 'restoreFormat', 'disposeFormatResources']) registryContext[name] = (...args) => calls.push([name, ...args])
vm.runInNewContext(registry[0] + '; registerReaderFormatAdapters();', registryContext)
assert.deepStrictEqual([...registered.keys()].sort(), [...Object.keys(expected), 'pdf-pages', 'audio', 'video'].sort())
for (const [mode, [open, render]] of Object.entries(expected)) {
  assert.strictEqual(registered.get(mode).open, registryContext[open], mode + ' loader')
  assert.strictEqual(registered.get(mode).render, registryContext[render], mode + ' renderer')
}
registered.get('pdf-pages').open()
assert.deepStrictEqual(calls.splice(0), [['preloadPdfFirstPage'], ['fetchReaderResponse']])
assert.strictEqual(registered.get('pdf-pages').render, registryContext.renderPdfPages)
for (const mode of ['audio', 'video']) {
  assert.strictEqual(registered.get(mode).open, registryContext.loadMediaDocument)
  registered.get(mode).render()
  assert.deepStrictEqual(calls.splice(0), [['renderMedia', mode]])
}
for (const [mode, adapter] of registered) {
  const entry = { page: 2 }
  adapter.restore(entry, 17)
  adapter.dispose()
  assert.deepStrictEqual(calls.splice(0), [['restoreFormat', mode, entry, 17], ['disposeFormatResources', mode]])
}
const html = fs.readFileSync(path.join(root, 'static/reader.html'), 'utf8')
const securityScript = html.indexOf('src="/search/static/reader-security.js"')
assert.ok(securityScript >= 0 && securityScript < html.indexOf('src="/search/static/reader-contract.js"'))
assertCode(reader, 'readerRuntime.track(window.__VOICE_PDF_PRELOAD__)')
console.log('reader architecture contracts passed')
